# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
__all__ = [
    "sum_as_string",
]

def sum_as_string(a: builtins.int, b: builtins.int) -> builtins.str:
    r"""
    Formats the sum of two numbers as string.
    """

