# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import os
import pathlib
import typing

__all__ = [
    "ArrayIndex",
    "DependencyClause",
    "DependencyJobRef",
    "DependencyJoin",
    "DependencyType",
    "JobTimeLimit",
    "MailType",
    "MailTypeInput",
    "Memory",
    "MemoryUnit",
    "ResourceSpec",
    "ResourceSpecCPU",
    "ResourceSpecGPU",
    "SlurmArraySpec",
    "SlurmDependency",
    "SlurmJobConfig",
    "SlurmSignalSpec",
]

@typing.final
class ArrayIndex:
    r"""
    Wraps the [`ArrayIndex`] sum type. Construct one of the three variants
    via the `single`/`range`/`stepped` classmethods. Inspect via `kind` plus
    the matching `value`/`start`/`end`/`step` accessors.
    """
    @property
    def kind(self) -> builtins.str:
        r"""
        Discriminant: `"single"`, `"range"`, or `"stepped"`.
        """
    @property
    def value(self) -> typing.Optional[builtins.int]:
        r"""
        `Some(i)` for `single`, else `None`.
        """
    @property
    def start(self) -> typing.Optional[builtins.int]:
        r"""
        `Some(start)` for `range`/`stepped`, else `None`.
        """
    @property
    def end(self) -> typing.Optional[builtins.int]:
        r"""
        `Some(end)` for `range`/`stepped`, else `None`.
        """
    @property
    def step(self) -> typing.Optional[builtins.int]:
        r"""
        `Some(step)` for `stepped`, else `None`.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    @staticmethod
    def single(i: builtins.int) -> ArrayIndex:
        r"""
        Single-index entry, e.g. `5`.
        """
    @staticmethod
    def range(start: builtins.int, end: builtins.int) -> ArrayIndex:
        r"""
        Inclusive range entry, e.g. `0-15`.
        """
    @staticmethod
    def stepped(
        start: builtins.int, end: builtins.int, step: builtins.int
    ) -> ArrayIndex:
        r"""
        Inclusive range with step, e.g. `0-15:4` (= 0, 4, 8, 12).
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DependencyClause:
    @property
    def dep_type(self) -> DependencyType: ...
    @dep_type.setter
    def dep_type(self, value: DependencyType) -> None: ...
    @property
    def job_refs(self) -> builtins.list[DependencyJobRef]: ...
    @job_refs.setter
    def job_refs(self, value: typing.Sequence[DependencyJobRef]) -> None: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls, dep_type: DependencyType, job_refs: typing.Sequence[DependencyJobRef] = []
    ) -> DependencyClause: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DependencyJobRef:
    @property
    def job_id(self) -> builtins.int: ...
    @property
    def delay_minutes(self) -> typing.Optional[builtins.int]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(
        cls, job_id: builtins.int, delay_minutes: typing.Optional[builtins.int] = None
    ) -> DependencyJobRef: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class JobTimeLimit:
    @property
    def total_seconds(self) -> builtins.int: ...
    @property
    def hours(self) -> builtins.int: ...
    @property
    def minutes(self) -> builtins.int: ...
    @property
    def seconds_part(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, s: builtins.str) -> JobTimeLimit:
        r"""
        Parse a Slurm `--time` spec string, e.g. `"01:00:00"` or `"3-12:00:00"`.
        """
    @staticmethod
    def parse(s: builtins.str) -> JobTimeLimit: ...
    @staticmethod
    def from_seconds(seconds: builtins.int) -> JobTimeLimit: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class MailTypeInput:
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, types: typing.Sequence[MailType]) -> MailTypeInput:
        r"""
        Build from a non-empty list of `MailType` variants. Empty list raises.
        """
    @staticmethod
    def parse(s: builtins.str) -> MailTypeInput:
        r"""
        Parse from the comma-separated Slurm form (`"BEGIN,END"`).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Memory:
    @property
    def value(self) -> builtins.int: ...
    @property
    def unit(self) -> MemoryUnit: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, s: builtins.str) -> Memory:
        r"""
        Parse a Slurm memory token, e.g. `"8G"` (or unit-less `"1024"` =
        mebibytes per Slurm `--mem` default).
        """
    @staticmethod
    def parse(s: builtins.str) -> Memory: ...
    @staticmethod
    def from_value(value: builtins.int, unit: MemoryUnit) -> Memory: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ResourceSpec:
    @property
    def kind(self) -> builtins.str:
        r"""
        `"cpu"` or `"gpu"`.
        """
    @property
    def cpu_spec(self) -> typing.Optional[ResourceSpecCPU]: ...
    @property
    def gpu_spec(self) -> typing.Optional[ResourceSpecGPU]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        processes: typing.Optional[builtins.int] = None,
        threads: typing.Optional[builtins.int] = None,
        cores: typing.Optional[builtins.int] = None,
        memory: typing.Optional[Memory] = None,
        gpus: typing.Optional[builtins.int] = None,
    ) -> ResourceSpec:
        r"""
        Build a `ResourceSpec` from individual KUDPC `--rsc` keys.

        All keyword arguments are optional. CPU keys
        (`processes`, `threads`, `cores`, `memory`) and the GPU key
        (`gpus`) are mutually exclusive — passing any of the former
        together with the latter raises `ValueError`. Each integer
        key must be `>= 1`. The `memory` parameter must be a
        [`PyMemory`] instance — wrap a string with `Memory("2G")` or
        `Memory.from_value(2, MemoryUnit.Giga)` first.
        """
    @staticmethod
    def from_str(s: builtins.str) -> ResourceSpec:
        r"""
        Parse a Slurm `--rsc` spec, e.g. `"p=4:t=8:c=8:m=8G"` or `"g=1"`.
        """
    @staticmethod
    def parse(s: builtins.str) -> ResourceSpec:
        r"""
        Backwards-compatible alias for [`Self::from_str`].
        """
    @staticmethod
    def cpu(spec: ResourceSpecCPU) -> ResourceSpec: ...
    @staticmethod
    def gpu(spec: ResourceSpecGPU) -> ResourceSpec: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ResourceSpecCPU:
    @property
    def p(self) -> typing.Optional[builtins.int]:
        r"""
        Returns `None` if `p` was not specified.
        """
    @property
    def t(self) -> typing.Optional[builtins.int]:
        r"""
        Returns `None` if `t` was not specified.
        """
    @property
    def c(self) -> typing.Optional[builtins.int]:
        r"""
        Returns `None` if `c` was not specified.
        """
    @property
    def m(self) -> typing.Optional[Memory]:
        r"""
        Returns `None` if `m` was not specified.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls, p: builtins.int, t: builtins.int, c: builtins.int, m: Memory
    ) -> ResourceSpecCPU:
        r"""
        Construct a fully-specified CPU resource spec — all four of
        (`p`, `t`, `c`, `m`) are required positional arguments.
        For partial specs (e.g. `p=60:t=1:c=1` per the KUDPC manual),
        use [`PyResourceSpec`]'s positional/kwargs constructor instead.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ResourceSpecGPU:
    @property
    def g(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, g: builtins.int) -> ResourceSpecGPU: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SlurmArraySpec:
    @property
    def indices(self) -> builtins.list[ArrayIndex]: ...
    @indices.setter
    def indices(self, value: typing.Sequence[ArrayIndex]) -> None: ...
    @property
    def max_concurrent(self) -> typing.Optional[builtins.int]: ...
    @max_concurrent.setter
    def max_concurrent(self, value: typing.Optional[builtins.int]) -> None: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, s: builtins.str) -> SlurmArraySpec:
        r"""
        Parse a Slurm `--array` spec string, e.g. `"0-15:4%2"`.
        """
    @staticmethod
    def parse(s: builtins.str) -> SlurmArraySpec: ...
    @staticmethod
    def from_indices(
        indices: typing.Sequence[ArrayIndex],
        max_concurrent: typing.Optional[builtins.int] = None,
    ) -> SlurmArraySpec:
        r"""
        Build from an explicit list of entries plus an optional concurrency cap.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SlurmDependency:
    @property
    def clauses(self) -> builtins.list[DependencyClause]: ...
    @clauses.setter
    def clauses(self, value: typing.Sequence[DependencyClause]) -> None: ...
    @property
    def join(self) -> DependencyJoin: ...
    @join.setter
    def join(self, value: DependencyJoin) -> None: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, s: builtins.str) -> SlurmDependency:
        r"""
        Parse a Slurm `--dependency` spec string, e.g. `"afterok:200"`.
        """
    @staticmethod
    def parse(s: builtins.str) -> SlurmDependency: ...
    @staticmethod
    def from_clauses(
        clauses: typing.Sequence[DependencyClause],
        join: DependencyJoin = DependencyJoin.And,
    ) -> SlurmDependency:
        r"""
        Build directly from clauses + join.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SlurmJobConfig:
    @property
    def partition(self) -> builtins.str: ...
    @partition.setter
    def partition(self, value: builtins.str) -> None: ...
    @property
    def time_limit(self) -> typing.Optional[JobTimeLimit]: ...
    @time_limit.setter
    def time_limit(self, value: typing.Optional[JobTimeLimit]) -> None: ...
    @property
    def log_stdout(self) -> typing.Optional[pathlib.Path]: ...
    @log_stdout.setter
    def log_stdout(
        self, value: typing.Optional[builtins.str | os.PathLike | pathlib.Path]
    ) -> None: ...
    @property
    def log_stderr(self) -> typing.Optional[pathlib.Path]: ...
    @log_stderr.setter
    def log_stderr(
        self, value: typing.Optional[builtins.str | os.PathLike | pathlib.Path]
    ) -> None: ...
    @property
    def comment(self) -> typing.Optional[builtins.str]: ...
    @comment.setter
    def comment(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def job_name(self) -> typing.Optional[builtins.str]: ...
    @job_name.setter
    def job_name(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def array_spec(self) -> typing.Optional[SlurmArraySpec]: ...
    @array_spec.setter
    def array_spec(self, value: typing.Optional[SlurmArraySpec]) -> None: ...
    @property
    def dependency(self) -> typing.Optional[SlurmDependency]: ...
    @dependency.setter
    def dependency(self, value: typing.Optional[SlurmDependency]) -> None: ...
    @property
    def mail_user(self) -> typing.Optional[builtins.str]: ...
    @mail_user.setter
    def mail_user(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def mail_types(self) -> typing.Optional[MailTypeInput]: ...
    @mail_types.setter
    def mail_types(self, value: typing.Optional[MailTypeInput]) -> None: ...
    @property
    def resource_spec(self) -> typing.Optional[ResourceSpec]: ...
    @resource_spec.setter
    def resource_spec(self, value: typing.Optional[ResourceSpec]) -> None: ...
    def __new__(
        cls,
        partition: builtins.str,
        time_limit: typing.Optional[JobTimeLimit] = None,
        log_stdout: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None,
        log_stderr: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None,
        comment: typing.Optional[builtins.str] = None,
        job_name: typing.Optional[builtins.str] = None,
        array_spec: typing.Optional[SlurmArraySpec] = None,
        dependency: typing.Optional[SlurmDependency] = None,
        mail_user: typing.Optional[builtins.str] = None,
        mail_types: typing.Optional[MailTypeInput] = None,
        resource_spec: typing.Optional[ResourceSpec] = None,
    ) -> SlurmJobConfig: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class SlurmSignalSpec:
    @property
    def allow_resignal(self) -> builtins.bool: ...
    @property
    def signal(self) -> builtins.str: ...
    @property
    def seconds_before_end(self) -> typing.Optional[builtins.int]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, s: builtins.str) -> SlurmSignalSpec:
        r"""
        Parse a Slurm `--signal` spec string, e.g. `"USR1@60"` or `"R:SIGTERM@30"`.
        """
    @staticmethod
    def parse(s: builtins.str) -> SlurmSignalSpec: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DependencyJoin(enum.Enum):
    And = ...
    r"""
    Comma-separated — every clause must be satisfied.
    """
    Or = ...
    r"""
    `?`-separated — any one clause being satisfied releases the job.
    """

    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class DependencyType(enum.Enum):
    After = ...
    AfterAny = ...
    AfterBurstBuffer = ...
    AfterCorr = ...
    AfterNotOk = ...
    AfterOk = ...
    Singleton = ...

    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class MailType(enum.Enum):
    BEGIN = ...
    END = ...
    FAIL = ...
    REQUEUE = ...
    ALL = ...

    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class MemoryUnit(enum.Enum):
    Kilo = ...
    Mega = ...
    Giga = ...
    Tera = ...

    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
