# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing

__all__ = [
    "JobReason",
    "JobState",
    "JobStatus",
]

@typing.final
class JobReason:
    r"""
    Wraps [`inner::JobReason`]. Construct common variants via class
    methods (`none()`, `priority()`, …), supply an arbitrary SLURM
    reason string via `parse(raw)`, or attach an unknown raw string with
    `other(raw)`.

    Inspect with `name` (variant identifier — `"None"`, `"Priority"`, or
    `"Other"` for an unrecognized reason), `value` (the canonical SLURM
    string for known variants, or the raw stored string for `Other`),
    or `__str__` (same as `value`).
    """
    @property
    def name(self) -> builtins.str:
        r"""
        Variant name. `"None"`, `"Priority"`, `"Resources"`, `…`, or
        `"Other"` (use `value` to get the raw string of an `Other`).
        """
    @property
    def value(self) -> builtins.str:
        r"""
        Canonical SLURM reason string (`"None"`, `"Priority"`, …). For
        `Other(raw)` returns the stored raw string verbatim.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    @staticmethod
    def none() -> JobReason:
        r"""
        SLURM `"None"` — typically a running job, no waiting reason.
        """
    @staticmethod
    def priority() -> JobReason:
        r"""
        `"Priority"` — waiting on a higher-priority job.
        """
    @staticmethod
    def resources() -> JobReason:
        r"""
        `"Resources"` — waiting on resource availability.
        """
    @staticmethod
    def dependency() -> JobReason:
        r"""
        `"Dependency"` — waiting on a parent job to finish.
        """
    @staticmethod
    def begin_time() -> JobReason:
        r"""
        `"BeginTime"` — held until the job's `--begin` time.
        """
    @staticmethod
    def time_limit() -> JobReason:
        r"""
        `"TimeLimit"` — terminated for hitting wall-time.
        """
    @staticmethod
    def out_of_memory() -> JobReason:
        r"""
        `"OutOfMemory"` — terminated by an OOM kill.
        """
    @staticmethod
    def non_zero_exit_code() -> JobReason:
        r"""
        `"NonZeroExitCode"` — terminated by a non-zero exit.
        """
    @staticmethod
    def job_held_user() -> JobReason:
        r"""
        `"JobHeldUser"` — held by user (`scontrol hold`).
        """
    @staticmethod
    def job_held_admin() -> JobReason:
        r"""
        `"JobHeldAdmin"` — held by admin.
        """
    @staticmethod
    def parse(raw: builtins.str) -> JobReason:
        r"""
        Parse any SLURM reason string. Empty / `"None"` → `None`;
        known PascalCase strings → matching variant; anything else →
        `Other(raw)`.
        """
    @staticmethod
    def other(raw: builtins.str) -> JobReason:
        r"""
        Construct an explicit `Other(raw)` variant. The raw string is
        stored verbatim, even if it matches a known canonical name —
        use `parse` if you want auto-routing to the matching variant.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class JobStatus:
    r"""
    Wraps [`inner::JobStatus`] — a `(state, reason)` pair mirroring one
    `squeue %T %r` row. Build with `JobStatus(state, reason)` (reason
    defaults to `JobReason.none()`), or via the convenience constructor
    `JobStatus.parse(state_token, reason_str)`.
    """
    @property
    def state(self) -> JobState: ...
    @property
    def reason(self) -> JobReason: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, state: JobState, reason: JobReason = ...) -> JobStatus: ...
    @staticmethod
    def parse(state: builtins.str, reason: builtins.str = "") -> JobStatus:
        r"""
        Build a status by parsing the `(state, reason)` pair as raw
        SLURM strings (e.g. `JobStatus.parse("PD", "Priority")`).
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class JobState(enum.Enum):
    Pending = ...
    Configuring = ...
    Requeued = ...
    RequeueFed = ...
    RequeueHold = ...
    ResvDelHold = ...
    Suspended = ...
    Stopped = ...
    Running = ...
    Completing = ...
    Resizing = ...
    Signaling = ...
    StageOut = ...
    Completed = ...
    BootFail = ...
    Cancelled = ...
    Deadline = ...
    Failed = ...
    NodeFail = ...
    OutOfMemory = ...
    Preempted = ...
    Revoked = ...
    SpecialExit = ...
    Timeout = ...
    Unknown = ...

    @property
    def token(self) -> builtins.str:
        r"""
        SLURM long-form token, e.g. `"PENDING"`, `"OUT_OF_MEMORY"`.
        """
    @staticmethod
    def parse(raw: builtins.str) -> JobState:
        r"""
        Parse a raw SLURM state token (long form, compact code, trailing
        context, or any case). Falls back to `Unknown`.
        """
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
